First commit, basic functions
Teaching-projects/SZE-MOSZE-2020-Nehez-eldonteni pull request #1
Opened 2020-09-12 12:21 UTC by haliscsharp

First task, functioning

2020-09-13 21:14 UTC, hegyhati requested changes
Nagyjabol rendben, de par jelzett dolgot modosits/gondolkodjatok el rajta.

2020-09-13 21:14 UTC, hegyhati commented on character.cpp
> +}
Ennek mi ertelme?

2020-09-13 21:14 UTC, hegyhati commented on character.h
> +		currentHP = maxHP;
ez miert nem inicializalo listaban?

2020-09-13 21:14 UTC, hegyhati commented on character.h
> +	bool isDead() { return currentHP == 0; }
const?

2020-09-13 21:14 UTC, hegyhati commented on character.h
> +	void takeDamage(character* opponent) { (currentHP - opponent->getAttack() < 0) ? currentHP = 0 : currentHP -= opponent->getAttack(); }
Nem lenne egyszerubb referenciakkal pointerek helyett? Illetve const-okat itt is tessek bepakolni oda ahova kell.

2020-09-13 21:14 UTC, hegyhati commented on main.cpp
> +	delete ch2;
Mi volt a haszna, hogy dinamikusan csinaltad?

2020-09-15 14:18 UTC, hegyhati requested changes

2020-09-15 14:18 UTC, hegyhati commented on character.h
> +	//int getMaxHP() { return maxHP; }
Kikommentelt kod ne maradjon. Vagy legyen ott, vagy ne. Ha valami kell, akkor legyen. HA nem, akkor van git history a regi dolgot eloszedni.

2020-09-15 14:18 UTC, hegyhati commented on character.h
> +	int attack;
const? (ahol logikus)

2020-09-15 14:19 UTC, hegyhati commented
Ach, tul gyorsan kattintottam. Szoval ket aprosag, gyorsan tegyetek rendbe, taggeljetek egy kommentben, hogy kesz, aztan beviszem.

2020-09-15 15:03 UTC, haliscsharp commented on character.h
> +	int attack;
Kész. @hegyhati

2020-09-15 15:04 UTC, merged