Game and Map
Teaching-projects/SZE-MOSZE-2020-Nehez-eldonteni pull request #15
Opened 2020-11-23 15:19 UTC by AnonymDavid

Game and Map task merged together.

2020-11-23 20:24 UTC, joostibor requested changes
Az a két üres konstruktor fura. Ha kell akkor oké, nem szóltam, de ha megy nélküle szerintem törlés. Másik megjegyzés, hogy a publikus dolgokról egy nagyon rövid doxygen jól jöhet.
Egyébként szép megoldások, több helyen is :sunglasses: :+1:

2020-11-23 20:24 UTC, joostibor commented on Game.cpp
> +                // if the map given is not rectangle fill the rest with wall
Kommenteket majd ne hagyj benne szerintem.

2020-11-23 20:24 UTC, joostibor commented on Game.cpp
> +                // if the map given is not rectangle fill the rest with wall
Vagy ha doxygenbe szántad, akkor tegyél egy harmadik /-t :D

2020-11-23 20:24 UTC, joostibor commented on Game.h
> +    // exceptions
akárcsak az előbb

2020-11-23 20:24 UTC, joostibor commented on Hero.h
> +	Hero() {}
erre van szükség?

2020-11-23 20:24 UTC, joostibor commented on Monster.h
> +	Monster() {}
?

2020-11-23 20:35 UTC, AnonymDavid commented
Javítva

2020-11-23 20:38 UTC, joostibor approved these changes
Ámen, mehet be 👍

2020-11-26 20:45 UTC, Peti96 approved these changes
👍👌

2020-11-26 20:49 UTC, haliscsharp approved these changes

2020-11-26 20:54 UTC, merged