Feladat #2
Teaching-projects/SZE-MOSZE-2020-Nehez-eldonteni pull request #2
Opened 2020-09-19 11:19 UTC by AnonymDavid

2020-09-21 14:54 UTC, hegyhati commented
Reagalni fogok ra, csak most priot elveznek az elso hetes feladatok meg. Addig is a description-t ha engedi, akkor meg tessek update-elni.

2020-09-23 00:55 UTC, hegyhati requested changes
Par aprosag + a parzolast atlathatova kell tenni. 

Ezen kivul a vart kimenetnek es maga a teszt script sem a legjobb helyen van a forras mellett, valami alkonyvtarba el kellene pakolni, es a unitoknak is ott kellene lenni mellettuk. 

Ha mozgattok, atneveztek, akkor FONTOS hogy `git mv`-vel, ne csak ugy a fajlrendszerben, mert akkor a git nem tudja lekovetni.

2020-09-23 00:55 UTC, hegyhati commented on diff_script.sh
> +./a.out units/halis.json units/codos.json > fight.txt
Kicsit trukkos, hogy itt `>` utana meg `>>` elrejti azt, hogy ha volt, torolnenk. Atlathatobb (bar ketsegkivul hosszabb), ha ez nem side effectkent, hanem expliciten megjelenik.

2020-09-23 00:55 UTC, hegyhati commented on diff_script.sh
> +DIFF=$(diff fight.txt manual_calculation.txt)
itt megcsinalod ezt a DIFF-et, aztan a workflow-ban is meghivod meg egyszer. Igy redundansan ne legyen. Terjen vissza akkor ez a fuggveny a DIFF eredmenyevel, es ott ne legyen emg egyszer lefuttatva a diff.

2020-09-23 00:55 UTC, hegyhati commented on diff_script.sh
> +DIFF=$(diff fight.txt manual_calculation.txt)
MArmint a script terjen vissza 0-val ha a DIFF ures, es hibakoddal ha nem.

2020-09-23 00:55 UTC, hegyhati commented on main.cpp
> +	}
Ha sikeresen lement a main, akkor terjen vissza 0-val, ha nem, akkor valami hibakoddal.

2020-09-23 00:55 UTC, hegyhati commented on character.cpp
> +*/
Ilyen szemeteket ne hagyjunk a kodban.

2020-09-23 00:55 UTC, hegyhati commented on README.md
> +We created a Git Actions pipeline that tests the program on every push with the help of our shell script.
Akkor mar lehetne konzisztens, hogy "van", nem pedig "csinaltunk".

2020-09-23 00:55 UTC, hegyhati commented on FileNotFoundException.h
> +#endif
Alapvetoen ez igy rendben van, de igy semmi ertelme nincs az std::exception-bol valo szarmaztatasnak. Ha abbol szarmaztattok, akkor a `what`-ot illene feluldefinialni. Es mivel a message az lesz, hogy "File not found", ezert a konstans literalert teljesen felesleges felvenni egy string adattagot. Arra akkor lenne szukseg, ha a fajl nevet is kiirnatok, ami amugy nem lenne hulyeseg. Es persze akkor ez const, mert nem nagyon valtozik.

Vagy mivel az exception-on kivul siman csak egy string-et tarol az egesz... akar szarmazhatna abbol is, akkor rogton meglenne ra a << operator meg minden. Magic.

2020-09-23 00:55 UTC, hegyhati commented on character.cpp
> +	}
Ezt nem ertem. Ha van egy ilyen exception, akkor elkapod, aztan tovabbdobod? Ennek mi ertelme?

2020-09-23 00:55 UTC, hegyhati commented on .github/workflows/output_test.yml
> +        build:
job nev nem tul kifejezo.

2020-09-23 00:55 UTC, hegyhati commented on character.cpp
> +#include "FileNotFoundException.h"
Legyunk konzisztensek fajl/osztaly elnevezesi konvenciokban. Szoval vagy `Character`-re legyen refaktoralas (ez lenne celszeru), vagy `file_not_found_exception`.  Csak legyen egyseges.

2020-09-23 00:55 UTC, hegyhati commented on character.cpp
> +character character::parseUnit(std::string fileName)
feleslegesen masoljuk le a filenevet.

2020-09-23 00:55 UTC, hegyhati commented on character.cpp
> +				if (end < 0)
itt npos-ra akarsz tesztelni?

2020-09-23 00:55 UTC, hegyhati commented on character.cpp
> +					first = line.find(":", last + 2) + 1;
na, ez a kod kelloen kaotikus, a `first` valtozodat ujrahasznalod, kisse atlathatatlan, hogy melyik agban mi tortenik, stb. Kesobb ez meg bonyolodni fog, szoval erdemes msot letisztazni. 

Erdemes lenne kiszervezni "kompakt" dolgokat, amiket tobbszor hasznaltok. Mondjuk pl egy `"akarmi"` beparzolasat az input stream-rol. Ezzel mar a kod atlathatosaga nagyban novelheto. De nems okkal lenne mondjuk bonyolultabb megcsinalni akkor egy `OneLevelJSONParser` osztalyt, ami csak ilyen egyszeru kulcs-ertek parokat parzol, es visszaad egy `map<string,string>`-et mondjuk. Es akkor itt csak ezt rakulditek, aztan vegigmentek a map-en. Hogy mennyire mentek el ebbe az iranyba, az Ratok van bizva, de ennel atlathatobb legyen a kod.

2020-09-23 15:14 UTC, haliscsharp commented on character.cpp
> +					first = line.find(":", last + 2) + 1;
@hegyhati Készen vagyunk a változtatásokkal.

2020-09-24 15:34 UTC, hegyhati approved these changes
Egy aprosag volt csak. Szedjetek ki azt a destruktort, commit messageben legyen hogy "@hegyhati mehet a merge", aztan beviszem. Most nem sietos a dolog, Ti jol alltok. 

A beolvasas elegge "fix" de majd a kovetkezo feladatnal ez ugyis kijon :-)

2020-09-24 15:34 UTC, hegyhati commented on FileNotFoundException.h
> +	~FileNotFoundException() {}
Ennek sok ertelme nincs.

2020-09-24 22:27 UTC, merged