Levelup
Teaching-projects/SZE-MOSZE-2020-Nehez-eldonteni pull request #6
Opened 2020-10-14 16:46 UTC by nemethvalentin

Created new adventurer class which can level up after every 100 XP. Also made a GHA to test the program if it has memory leaks or any errors or warning in the code.

2020-10-17 13:26 UTC, oliverosz requested changes
Csak pár apróságot találtam, amit javítani kell. Ha ez megvan, akkor frissítsétek a branchet a masterre, és oldjátok fel a conflictokat, csak utána kérjetek újabb review-t.

2020-10-17 13:26 UTC, oliverosz commented on Main.cpp
> +	delete ch2;
Ha exceptiont dob a try blokk, akkor nem kerülnek felszabadításra.

2020-10-17 13:26 UTC, oliverosz commented on Main.cpp
> +	(void)argc;
Ez azért van itt, hogy ne panaszkodjon a fordító unused paraméterre? Mert akkor egyszerűbb nem elnevezni a paramétert. De amúgy meg nem ártana ellenőrizni az `argc`-t, nehogy kiindexeljen az `argv`ből.

2020-10-17 13:26 UTC, oliverosz commented on Adventurer.cpp
> +int Adventurer::takeDamage(Character& opponent) {
Ez ugyanaz, mint a `Character::takeDamage`, nem? Miért van itt is definiálva?

2020-10-19 11:55 UTC, nemethvalentin commented
@oliverosz Megcsináltam a kért módosításokat.

2020-10-19 15:33 UTC, oliverosz reviewed
> @oliverosz Megcsináltam a kért módosításokat.

Azt meg, de ezt is kértem: "Ha ez megvan, akkor frissítsétek a branchet a masterre, és oldjátok fel a conflictokat, csak utána kérjetek újabb review-t."

2020-10-19 15:33 UTC, oliverosz commented on Main.cpp
> +	}catch (std::runtime_error e)
Kivételeket mindig referenciaként kapunk el, nem érték szerint.

2020-10-19 20:17 UTC, nemethvalentin commented
@oliverosz Feloldottuk a conflictokat.

2020-10-20 15:17 UTC, oliverosz requested changes

2020-10-20 15:17 UTC, oliverosz commented on Adventurer.h
> +	void increaseXP(int xpAmmount);
Hopp, ez a merge után privátból publikus lett. Dugd el gyorsan!

2020-10-20 15:17 UTC, oliverosz commented on Adventurer.cpp
> +	this->currentCooldown += this->cooldown;
Ez benne van a `Character::attackEnemy`ben is. Így duplán adódik hozzá a cooldown, ha jól látom.

2020-10-20 15:17 UTC, oliverosz commented on testing/units/kowa.json
> +	"attackcooldown": 5.5
a `dmg` és az `attackcooldown` kulcs-érték párok között nincs vessző (többi json fájlban sem)

2020-10-20 16:04 UTC, nemethvalentin commented
@oliverosz Javítottuk a hibákat.

2020-10-21 11:25 UTC, nemethvalentin commented
@oliverosz Hozzáadtuk a kifelejtett 10%-os cooldown csökkenést szintlépéskor.

2020-10-21 14:39 UTC, oliverosz commented on Adventurer.h
> +	void increaseXP(int xpAmmount);
Az increaseXP-re gondoltam, nem az attackEnemyre.

2020-10-21 14:42 UTC, oliverosz requested changes
Az nem jó, hogy az `Adventurer::attackEnemy` privát, az XP növelést kellett volna elrejteni kifelé.

2020-10-21 15:12 UTC, oliverosz approved these changes

2020-10-21 15:12 UTC, merged